art/urls.py
from django.conf.urls import *

# place app url patterns here
from art import views


urlpatterns = patterns('',
                       url(r'^paintings/(?P<slug>[-\w]+)$', views.PaintingDetailView.as_view(), name='painting-detail'),
                       url(r'^paintings/$', views.PaintingListView.as_view(), name='painting-listview'),

                       url(r'^artists/$', views.ArtistListView.as_view(), name='artist-listview'),

                       url(r'^places/(?P<slug>[-\w]+)$', views.PlaceDetailView.as_view(), name='place-detail'),

                       url(r'^articles/symbols/(?P<slug>[-\w]+)$', views.SymbolDetailView.as_view(), name='symbol-detail'),
                       url(r'^articles/symbols/$', views.SymbolListView.as_view(), name='symbol-listview'),

                       url(r'^articles/events/(?P<slug>[-\w]+)$', views.EventDetailView.as_view(), name='event-detail'),
                       url(r'^articles/events/$', views.EventListView.as_view(), name='event-listview'),

                       url(r'^articles/persons/(?P<slug>[-\w]+)$', views.PersonDetailView.as_view(), name='person-detail'),
                       url(r'^articles/persons/$', views.PersonListView.as_view(), name='person-listview'),
                       )

art/models.py
import os
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
import django_countries
from django_extensions.db import fields
from imagekit.models import ImageSpecField
from pilkit.processors import SmartResize, ResizeToCover


def generic_upload(instance, filename):
    _, extension = os.path.splitext(filename)
    dirname = instance.__class__.__name__.lower()
    return "{0}/{1}/{2}{3}".format(dirname, instance.uuid, slugify(instance.name), extension)


class Thing(models.Model):

    class Meta:
        abstract = True

    schema = "http://schema.org/Thing"

    uuid = fields.UUIDField(version=4, primary_key=True)
    slug = fields.AutoSlugField(populate_from='name')
    created = fields.CreationDateTimeField()
    last_modified = fields.ModificationDateTimeField()

    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)

    image = models.ImageField(upload_to=generic_upload, max_length=300, null=True, blank=True)
    image_detail = ImageSpecField([ResizeToCover(570, 1)], source='image')
    image_summary = ImageSpecField([SmartResize(370, 370 / 1.61803398875)], source='image')
    image_thumbnail = ImageSpecField([SmartResize(150, 150)], source='image')

    sources = generic.GenericRelation('Source')

    def __unicode__(self):
        return u"{0}".format(self.name)

    def get_absolute_url(self):
        view = self.__class__.__name__.lower() + "-detail"
        return reverse(view, args=(self.slug,))


class Source(Thing):

    schema = "http://schema.org/Thing"

    content_type = models.ForeignKey(ContentType)
    object_id = fields.UUIDField()
    parent = generic.GenericForeignKey('content_type', 'object_id')


class Quote(Thing):

    schema = "http://schema.org/Thing"

    content_type = models.ForeignKey(ContentType)
    object_id = fields.UUIDField()
    parent = generic.GenericForeignKey('content_type', 'object_id')


class Address(Thing):

    schema = "http://schema.org/Address"

    street_address = models.CharField(max_length=300, null=True, blank=True)
    post_office_box_number = models.CharField(max_length=300, null=True, blank=True)
    postal_code = models.CharField(max_length=300, null=True, blank=True)
    address_locality = models.CharField(max_length=300)
    address_region = models.CharField(max_length=300, null=True, blank=True)
    address_country = django_countries.CountryField()

    def __unicode__(self):
        return u"{0}, {1}, {2}".format(self.street_address, self.address_locality, self.address_country)


class Place(Thing):

    schema = "http://schema.org/Place"

    address = models.ForeignKey(Address, blank=True, null=True)


class CreativeWork(Thing):

    class Meta:
        abstract = True

    date_created = models.CharField(max_length=100, blank=True, null=True)


class Painting(CreativeWork):

    schema = "http://schema.org/Painting"

    CATEGORY_CHOICES = (
        (0, 'Unknown'),
        (1, 'Bible'),
        (3, 'History'),
        (4, 'Mythology'),
    )

    TECHNIQUE_CHOICES = (
        (0, 'Unknown'),
        (1, 'Oil on Panel'),
    )

    category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES, default=0)
    technique = models.PositiveSmallIntegerField(choices=TECHNIQUE_CHOICES, default=0)

    author = models.ForeignKey('Person', related_name='created_paintings')
    content_location = models.ForeignKey('Place', null=True, blank=True)

    quotes = generic.GenericRelation('Quote')

    about_persons = models.ManyToManyField('Person', blank=True)
    about_events = models.ManyToManyField('Event', blank=True)
    mentions_symbols = models.ManyToManyField('Symbol', blank=True)


class Event(Thing):

    schema = "http://schema.org/Event"

    attendees = models.ManyToManyField(to='Person', blank=True)
    start_date = models.CharField(max_length=300, null=True, blank=True)
    end_date = models.CharField(max_length=300, null=True, blank=True)


class Person(Thing):

    schema = "http://schema.org/Person"

    birth_date = models.CharField(max_length=300, null=True, blank=True)
    death_date = models.CharField(max_length=300, null=True, blank=True)


class Symbol(Thing):

    schema = "http://schema.org/Thing"

art/forms.py
from django import forms

# place form definition here

art/views.py
from django.db.models import Count
from django.views.generic import DetailView, ListView
from art import models


class PaintingDetailView(DetailView):

    model = models.Painting


class PaintingListView(ListView):

    model = models.Painting


class PlaceDetailView(DetailView):
    
    model = models.Place
    
    
class SymbolDetailView(DetailView):

    model = models.Symbol


class SymbolListView(ListView):
    
    model = models.Symbol


class EventDetailView(DetailView):

    model = models.Event


class EventListView(ListView):

    model = models.Event


class PersonDetailView(DetailView):

    model = models.Person


class PersonListView(ListView):

    queryset = (models.Person.objects
                .annotate(num_paintings=Count('painting'))
                .filter(num_paintings__ge=1)
                .order_by("name"))


class ArtistListView(ListView):

    template_name = "art/artist_list.html"
    queryset = (models.Person.objects
                .annotate(num_paintings=Count('created_paintings'))
                .filter(num_paintings__ge=1)
                .order_by("name"))

art/templates/art/generic-aside.html
{% load arttags %}
{% load markup %}
<aside class="{{ model }} {{ size }} {% if object.image %}with-img{% else %}without-img{% endif %}" itemprop="{{ object.itemprop }}" itemscope
         itemtype="{{ object.schema }}">
    <h4>
        <a class="component-link" href="{{ object.get_absolute_url }}">
            <i class="icon {{ icon }}"></i> <span itemprop="name">{{ object.name }}</span>
        </a>
    </h4>

    {% if object.image %}
        <figure>
            <a href="{{ object.get_absolute_url }}" class="component-link">
                <img itemprop="image" src="{{ object.image_summary.url }}" alt="{{ object.name }}"/>
            </a>
        </figure>
    {% endif %}

    <div itemprop="description" class="description">
        {% block description %}{{ object.description|paragraphs:2|markdown }}{% endblock %}
    </div>

    {% block links %}
        <footer>
            <ul class="links">
                <li class="readmore">
                    <a itemprop="url" href="{{ object.get_absolute_url }}">Read more &raquo;</a>
                </li>
            </ul>
        </footer>
    {% endblock %}
</aside>

art/templates/art/generic-base.html
{% load arttags %}
{% load markup %}
<article class="{{ model }} {{ size }} {% if object.image %}with-img{% else %}without-img{% endif %}" itemscope
         itemtype="{{ object.schema }}">
    <header itemprop="name">
        {% block name %}
            <h1>{{ object.name }}</h1>
        {% endblock %}
        {% block subheader %}{% endblock %}
        {% block metadata %}
            <dl class="metadata">
                {% if object.category %}
                    <dt class="genre"><i class="icon-tag"></i><span>Filed under</span></dt>
                    <dd class="genre" itemprop="genre">{{ object.get_category_display }}</dd>
                {% endif %}
                {% if object.author %}
                    <dt class="author"><i class="icon-user"></i><span>By</span></dt>
                    <dd class="author"><a itemprop="creator"
                                          href="{{ object.author.get_absolute_url }}">{% schema_inline object.author %}</a>
                    </dd>
                {% endif %}
                {% if object.content_location %}
                    <dt class="location"><i class="icon-map-marker"></i><span>Location</span></dt>
                    <dd class="location"><a itemprop="contentLocation"
                                            href="{{ object.content_location.get_absolute_url }}">{% schema_inline object.content_location %}</a>
                    </dd>
                {% endif %}

                <dt class="published"><i class="icon-time"></i><span>Added on</span></dt>
                <dd class="published">
                    <time datetime="{{ object.created|date:"Y-m-d" }}">{{ object.created|date:"SHORT_DATE_FORMAT" }}</time>
                </dd>
            </dl>
        {% endblock %}
    </header>

    {% if object.image %}
        <figure>
            <a href="{{ object.get_absolute_url }}" class="component-link">
                <img itemprop="image" src="{% block image %}{% endblock %}" alt="{{ object.name }}"/>
            </a>
        </figure>
    {% else %}
        {% block no-image %}
            <div class="no-image"><i class="icon {{ icon }}"></i></div>{% endblock %}
    {% endif %}

    {% block before-description %}{% endblock %}

    <div itemprop="description" class="description">
        {% block description %}{{ object.description|markdown }}{% endblock %}
    </div>

    {% block before-additional-content %}{% endblock %}

    <div class="additional">
        {% block additional-content %}
        {% endblock %}
    </div>

    {% block links %}
        <footer>
            <ul class="links">
                <li class="permalink">
                    <a itemprop="url" href="{{ object.get_absolute_url }}">Permalink</a>
                </li>
                <li class="readmore">
                    <a itemprop="url" href="{{ object.get_absolute_url }}">Read more &raquo;</a>
                </li>
            </ul>
        </footer>
    {% endblock %}
</article>

art/templates/art/generic-full.html
{% extends "art/generic-base.html" %}
{% load arttags %}

{% block image %}{{ object.image.url }}{% endblock %}

{% block subheader %}
    {% if object.birth_date or object.death_date or object.start_date or object.end_date %}
        <small>
            <span itemprop="birthDate">{{ object.birth_date }}</span>
            <span itemprop="startDate">{{ object.start_date }}</span>
            {% if object.death_date or object.end_date %}
                {% if object.birth_date or object.start_date %}&mdash;{% endif %}
            {% endif %}
            <span itemprop="deathDate">{{ object.death_date }}</span>
            <span itemprop="endDate">{{ object.end_date }}</span>
        </small>
    {% endif %}
{% endblock %}

{% block before-description %}
    {% for quote in object.quotes.all %}
        {% schema_full quote %}
    {% endfor %}
{% endblock %}

{% block additional-content %}
    {% if object.event_set.all %}
        <aside class="related-events">
            <h4>Stories related to {{ object.name }}</h4>
            <ul>
                {% for event in object.event_set.all %}
                    <li itemprop="performerIn">
                        <a href="{{ event.get_absolute_url }}">{% schema_inline event %}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}

    {% if object.attendees.all %}
        <aside class="related-events">
            <h4>People mentioned in {{ object.name }}</h4>
            <ul>
                {% for attendee in object.attendees.all %}
                    <li itemprop="attendee">
                        <a href="{{ attendee.get_absolute_url }}">{% schema_inline attendee %}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}

    {% if object.painting_set.all %}
        <aside class="related-paintings">
            <h4>Paintings depicting {{ object.name }}</h4>
            <ul>
                {% for painting in object.painting_set.all %}
                    <li>
                        <a href="{{ painting.get_absolute_url }}">{% schema_thumb painting %}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}

    {% for event in object.about_events.all %}
        {% schema_aside event "about" %}
    {% endfor %}
    {% for person in object.about_persons.all %}
        {% schema_aside person "about" %}
    {% endfor %}
    {% for symbol in object.mentions_symbols.all %}
        {% schema_aside symbol "mentions" %}
    {% endfor %}

{% endblock %}

art/templates/art/generic-inline.html
<span class="{{ model }} {{ size }}" itemscope itemtype="{{ object.schema }}" itemprop="name">
{% block name %}{{ object.name }}{% endblock %}
</span>

art/templates/art/generic-summary.html
{% extends "art/generic-base.html" %}
{% load markup %}
{% load arttags %}

{% block image %}{{ object.image_summary.url }}{% endblock %}
{% block name %}
    <a class="component-link" href="{{ object.get_absolute_url }}">
        <h4>{{ object.name }}</h4>
    </a>
{% endblock %}
{% block description %}{{ object.description|paragraphs:1|markdown }}{% endblock %}

art/templates/art/generic-thumb.html
{% extends 'art/generic-base.html' %}

art/templates/art/painting-full.html
{% extends "art/generic-full.html" %}
{% block before-additional-content %}
    <h3>What do we see on this painting?</h3>
{% endblock %}

{% block subheader %}
    {% if object.date_created %}
        <span itemprop="dateCreated">{{ object.date_created }}</span>
    {% endif %}
    {% if object.date_created and object.technique %},{% endif %}
    {{ object.get_technique_display }}
{% endblock %}

art/templates/art/painting-thumb.html
{% load arttags %}
<article class="{{ model }} thumb" itemscope itemtype="{{ object.schema }}">
    <img itemprop="thumbnail" src="{{ object.image_summary.url }}" alt="{{ object.name }}"/>
    <div class="caption">
        <h4><span itemprop="name">{{ object.name }}</span>
        <small itemprop="author">{% schema_inline object.author %}</small></h4>
    </div>
</article>

art/templates/art/place-inline.html
<span class="{{ model }} {{ size }}" itemscope itemtype="{{ object.schema }}">
    <span itemprop="name">{{ object.name }}</span>,
    <span itemprop="address" itemscope itemtype="{{ object.address.schema }}">
        <span itemprop="address_locality">{{ object.address.address_locality }}</span>
    </span>
</span>

art/templates/art/quote-full.html
{% load markup %}
<div class="blockquote">
    <blockquote>
        {{ object.description|markdown }}
        <small><a href="{{ object.url }}" target="blank">{{ object.name }}</a></small>
    </blockquote>
</div>